### ISSUE TITLE
This dependency was not found in node_modules

### ISSUE THREAD

**Issue by yageek** [brandonxiang/vueleaflet#5]
I can not succeed to use the nom package using the vuejs web pack template.

I have this error when I try to import it:
```
import { MapComponent } from 'vue_leaflet'
```

I have the following error:
```
 ERROR  Failed to compile with 1 errors
This dependency was not found in node_modules:
* vue_leaflet
Did you forget to run npm install --save for it?
```

**Comment by brandonxiang** [comment]
I fix the problem by add parameter in `package.json`,

```
  "main": "dist/vue-leaflet.js",
```

all is because of `babel`. However, it still have some problem by npm package

```
ReferenceError: window is not defined
    at /Users/brandonxiang/test/example-vue-leaflet/node_modules/vue_leaflet/dist/vue-leaflet.js:32:12945
    at /Users/brandonxiang/test/example-vue-leaflet/node_modules/vue_leaflet/dist/vue-leaflet.js:32:12877
    at t.exports (/Users/brandonxiang/test/example-vue-leaflet/node_modules/vue_leaflet/dist/vue-leaflet.js:32:13163)
    at Object.<anonymous> (/Users/brandonxiang/test/example-vue-leaflet/node_modules/vue_leaflet/dist/vue-leaflet.js:32:13642)
    at e (/Users/brandonxiang/test/example-vue-leaflet/node_modules/vue_leaflet/dist/vue-leaflet.js:1:392)
    at Object.<anonymous> (/Users/brandonxiang/test/example-vue-leaflet/node_modules/vue_leaflet/dist/vue-leaflet.js:32:10163)
    at e (/Users/brandonxiang/test/example-vue-leaflet/node_modules/vue_leaflet/dist/vue-leaflet.js:1:392)
    at Object.<anonymous> (/Users/brandonxiang/test/example-vue-leaflet/node_modules/vue_leaflet/dist/vue-leaflet.js:1:527)
    at e (/Users/brandonxiang/test/example-vue-leaflet/node_modules/vue_leaflet/dist/vue-leaflet.js:1:392)
    at /Users/brandonxiang/test/example-vue-leaflet/node_modules/vue_leaflet/dist/vue-leaflet.js:1:485
```

**Comment by brandonxiang** [comment]
please use vueleaflet in the new branch vue2leaflet1
